### ISSUE TITLE
Endless loop in first fight with Maike

### ISSUE THREAD

**Issue by jvanbruegge** [WodkaRHR/Violet_Sources#7]
When the Lockschal uses Naturkraft it will become Sternenschauer, but then it loops back and says it will use Naturkraft.
After restarting and trying the fight again, this did not happen any more

**Comment by WodkaRHR** [comment]
> 
> 
> When the Lockschal uses Naturkraft it will become Sternenschauer, but then it loops back and says it will use Naturkraft.
> After restarting and trying the fight again, this did not happen any more

Fixed, thank you, Jan!
